ZKH.Blog.UI.Portal/Controllers/Admin/AdminPhotoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZKH.Blog.IBLL;
using ZKH.Blog.Model;
using ZKH.Blog.Model.Enum;

namespace ZKH.Blog.UI.Portal.Controllers.Admin
{
    public class AdminPhotoController : BaseController
    {
        IPhotoInfoService photoInfoService { get; set; }
        IPhotoTypeService photoTypeService { get; set; }
        short delFlagNormal = (short)DelFlagEnum.Normal;

        public ActionResult Index()
        {
            var typeList = photoTypeService.GetEntities(a => a.DelFlag == delFlagNormal).ToList();
            ViewBag.Types = typeList;
            return View();
        }

        public ActionResult DeleteType(string ids)
        {
            string[] strIds = ids.TrimEnd(',').Split(',');
            List<int> dellist = new List<int>();
            for (int i = 0; i < strIds.Length; i++)
            {
                dellist.Add(Int32.Parse(strIds[i]));
            }

            if (photoTypeService.DeleteListByLogical(dellist))
            {
                List<int> cids = photoInfoService.GetEntities(a => dellist.Contains(a.PhotoTypeId) && a.DelFlag == delFlagNormal).Select(a => a.Id).ToList();
                photoInfoService.DeleteListByLogical(cids);
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }

        [ValidateAntiForgeryToken]
        public ActionResult CreateType(PhotoType photoType)
        {
            if(photoType.Type == null)
            {
                return Content("no:相册名称不能为空 ！");
            }
            var types = photoTypeService.GetEntities(a => a.Type == photoType.Type && a.DelFlag == delFlagNormal).ToList();
            if (types.Count > 0)
            {
                return Content("no:相册名称已存在 ！");
            }

            photoType.SubTime = DateTime.Now;
            photoType.ModifiedOn = DateTime.Now;
            photoType.DelFlag = delFlagNormal;
            if(photoTypeService.Add(photoType) != null)
            {
                return Content("ok:相册创建成功 ！");
            }
            return Content("no:相册创建失败，请重试 ！");
        }

        [HttpGet]
        public ActionResult UpdateType(int id)
        {
            var type = photoTypeService.GetEntities(a => a.Id == id).FirstOrDefault();
            return View(type);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateType(PhotoType photoType)
        {
            if(photoType.Type == null)
            {
                return Content("no:相册名称不能为空 ！");
            }
            var types = photoTypeService.GetEntities(a => a.Type == photoType.Type && a.DelFlag == delFlagNormal && a.Id != photoType.Id).ToList();
            if (types.Count > 0)
            {
                return Content("no:相册名称已存在 ！");
            }
            var type = photoTypeService.GetEntities(a => a.Id == photoType.Id).FirstOrDefault();
            type.SubTime = photoType.SubTime;
            type.DelFlag = photoType.DelFlag;
            type.Type = photoType.Type;
            type.Remark = photoType.Remark;
            type.ModifiedOn = DateTime.Now;
            if (photoTypeService.Update(type))
            {
                return Content("ok:相册修改成功 ！");
            }
            return Content("no:相册修改失败，请重试 ！");
        }

        public ActionResult Category(int id)
        {
            var type = photoTypeService.GetEntities(a => a.Id == id).FirstOrDefault();
            var typeList = photoTypeService.GetEntities(a => a.Id != id && a.DelFlag == delFlagNormal).ToList();
            var photoList = photoInfoService.GetEntities(a => a.PhotoTypeId == id && a.DelFlag == delFlagNormal).ToList();
            ViewBag.Type = type;
            ViewBag.Types = typeList;
            ViewBag.Photos = photoList;
            return View();
        }

        [ValidateAntiForgeryToken]
        public ActionResult UploadPhoto()
        {
            HttpPostedFileBase file = Request.Files["photoFile"];
            if (file != null)
            {
                int size = (int)Math.Ceiling((double)file.ContentLength / 1024);
                if (size > 20000)
                {
                    return Content("no:图片不能大于20MB !");
                }
                string fileName = Path.GetFileName(file.FileName);
                string fileExt = Path.GetExtension(fileName).ToLower();

                string[] exts = new string[] { ".jpeg", ".jpg", ".png", ".gif", ".ico" };
                if (!exts.Contains(fileExt))
                {
                    return Content("no:图片格式不正确 !");
                }

                string dir = "/UploadFiles/UploadImgs/Albums";
                Directory.CreateDirectory(Path.GetDirectoryName(Request.MapPath(dir)));
                string newfileName = Guid.NewGuid().ToString();
                string fullDir = dir + newfileName + fileExt;
                file.SaveAs(Request.MapPath(fullDir));
                return Content("ok:" + fullDir);
            }
            else
            {
                return Content("no:请选择图片 !");
            }
        }

        [ValidateAntiForgeryToken]
        public ActionResult Create(PhotoInfo photoInfo)
        {
            if(photoInfo.Title == null || photoInfo.Url == null)
            {
                return Content("no:图片和图片名称不能为空 ！");
            }
            var photos = photoInfoService.GetEntities(a => a.Title == photoInfo.Title && a.DelFlag == delFlagNormal && a.PhotoTypeId == photoInfo.PhotoTypeId).ToList();
            if (photos.Count > 0)
            {
                return Content("no:该图片名称已存在 ！");
            }
            photoInfo.DelFlag = delFlagNormal;
            photoInfo.SubTime = DateTime.Now;
            if (photoInfoService.Add(photoInfo) != null)
            {
                return Content("ok:图片添加成功 ！");
            }
            return Content("no:图片添加失败，请重试 ！");
        }

        public ActionResult Delete(string ids)
        {
            string[] strIds = ids.TrimEnd(',').Split(',');
            List<int> dellist = new List<int>();
            for (int i = 0; i < strIds.Length; i++)
            {
                dellist.Add(Int32.Parse(strIds[i]));
            }

            if (photoInfoService.DeleteListByLogical(dellist))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            var photo = photoInfoService.GetEntities(a => a.Id == id).FirstOrDefault();
            return View(photo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(PhotoInfo photoInfo)
        {
            if (photoInfo.Title == null || photoInfo.Url == null)
            {
                return Content("no:图片和图片名称不能为空 ！");
            }
            var photos = photoInfoService.GetEntities(a => a.Title == photoInfo.Title && a.DelFlag == delFlagNormal && a.Id != photoInfo.Id && a.PhotoTypeId == photoInfo.PhotoTypeId).ToList();
            if (photos.Count > 0)
            {
                return Content("no:该图片名称已存在 ！");
            }
            photoInfo.SubTime = DateTime.Now;
            if (photoInfoService.Update(photoInfo))
            {
                return Content("ok:图片修改成功 ！");
            }
            return Content("no:图片修改失败，请重试 ！");
        }

        [HttpPost]
        public ActionResult Move(string Ids, string TypeId)
        {
            if (string.IsNullOrEmpty(Ids))
            {
                return Content("no:请选择移动项 ！");
            }
            string[] strIds = Ids.TrimEnd(',').Split(',');
            List<int> movelist = new List<int>();
            for (int i = 0; i < strIds.Length; i++)
            {
                movelist.Add(Int32.Parse(strIds[i]));
            }
            int typeId = Int32.Parse(TypeId);
            if (photoInfoService.Move(movelist, typeId))
            {
                return Content("ok:图片移动成功 ！");
            }
            return Content("no:图片移动失败，请重试 ！");
        }

        public ActionResult Detail(int id)
        {
            var photo = photoInfoService.GetEntities(a => a.Id == id && a.DelFlag == delFlagNormal).FirstOrDefault();
            return View(photo);
        }
    }
}

ZKH.Blog.UI.Portal/Views/AdminPhoto/Category.cshtml
@{
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
    ViewBag.Title = "相册管理";
}
<div class="padding20 bg-white">
    <h1 class="text-light"><a href="/AdminPhoto/Index"><span class="mif-arrow-left"></span></a>&nbsp; @ViewBag.Type.Type (@ViewBag.Photos.Count)<span class="mif-images place-right"></span></h1>
    <hr class="thin bg-grayLighter">
    <button class="button primary" onclick="showDialog('createdialog')"><span class="mif-plus"></span> 添加</button>
    <button class="button success" onclick="update()"> 修改</button>
    <button class="button warning" onclick="move()"> 移动</button>
    <button class="button alert" onclick="confirmdel()"> 删除</button>
    <hr class="thin bg-grayLighter">
    <table class="dataTable border bordered" data-role="datatable" data-auto-width="false">
        <thead>
            <tr>
                <td style="width: 20px"></td>
                <td class="sortable-column" style="width: 100px">ID</td>
                <td class="sortable-column">图片</td>
                <td class="sortable-column">图片名称</td>
                <td class="sortable-column">创建时间</td>
                <td class="sortable-column"></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var photo in ViewBag.Photos)
            {
                <tr>
                    <td>
                        <label class="input-control checkbox small-check no-margin">
                            <input type="checkbox" class="cbox" value="@photo.Id">
                            <span class="check"></span>
                        </label>
                    </td>
                    <td>@photo.Id</td>
                    <td><img src="@photo.Url" style="height:100px" /></td>
                    <td>@photo.Title</td>
                    <td>@photo.SubTime</td>
                    <td><a href="javascript:void(0)" onclick="detail(@photo.Id)">查看</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div data-role="dialog,draggable" id="createdialog" class="padding20" data-overlay="true" data-close-button="true" data-overlay-color="op-dark" data-overlay-click-close="true">
    <div class="example" data-text="添加图片" style="overflow:auto;height:400px">
        @using (Ajax.BeginForm("Create", "AdminPhoto", new AjaxOptions() { OnSuccess = "afterCreate" }, new { id = "createform", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <input type="hidden" name="PhotoTypeId" value="@ViewBag.Type.Id" />
            <label>图片名称</label>
            <div>
                <input class="input-control full-size required" style="border-style:solid" name="Title" />
            </div>
            <label>图片</label>
            <div>
                <input type="hidden" class="required" name="Url" id="url" />
                <div class="input-control file full-size" data-role="input">
                    <input type="file" id="photoinput" accept="image/jpeg,image/gif,image/png" name="photoFile" onchange="uploadphoto(this)">
                    <button class="button"><span class="mif-folder"></span></button>
                </div>
                <label>图片需小于20MB，支持格式：.jpg , .png , .gif , .ico</label>
            </div>
            <div class="cell" id="photoDiv" style="padding:0px 100px"></div>
            <br />
            <label>描述</label>
            <div class="input-control textarea full-size">
                <textarea name="Remark"></textarea>
            </div>
            <input class="primary" type="submit" onclick="return checkform()" value="确定" />
            <input class="button link" type="reset" value="重置" />
        }
    </div>
</div>
<div data-role="dialog,draggable" id="updatedialog" class="padding20" data-overlay="true" data-close-button="true" data-overlay-color="op-dark" data-overlay-click-close="true">
    <iframe id="updateform" width="600px" height="400px" frameborder="0"></iframe>
</div>
<div data-role="dialog,draggable" id="movedialog" class="padding20" data-overlay="true" data-close-button="true" data-overlay-color="op-dark" data-overlay-click-close="true">
    <div class="example" data-text="移动图片" style="overflow:auto;height:400px;width:300px">
        @using (Ajax.BeginForm("Move", new AjaxOptions() { OnSuccess = "afterMove" }))
        {
            @Html.AntiForgeryToken()
            <input type="hidden" name="Ids" id="moveids" />
            <h3>移动到</h3><hr class="thin" />
            foreach (var type in ViewBag.Types)
            {
                <div class="row">
                    <label class="input-control radio">
                        <input type="radio" name="TypeId" checked="checked" value="@type.Id">
                        <span class="check"></span>
                        <span class="caption">@type.Type</span>
                    </label>
                </div>
            }
            <input class="primary" type="submit" value="移动" />
        }
    </div>
</div>
<div data-role="dialog,draggable" id="detaildialog" class="padding20" data-overlay="true" data-close-button="true" data-overlay-color="op-dark" data-overlay-click-close="true">
    <iframe id="detailform" width="600px" height="400px" frameborder="0"></iframe>
</div>
<style type="text/css">
    label.error {
        color: red;
    }

    .field-validation-error {
        color: red;
    }
</style>
<script src="~/Scripts/MyAjaxForm.js"></script>
<script type="text/javascript">
    $(function () {
        $("#createform").validate({
            messages: {
                Title: { required: "*必填" },
            },
            errorPlacement: function (error, element) {
                error.appendTo(element.parent());
            }
        });
    });

    function checkform() {
        if ($("#url").val() === "") {
            alert("请选择图片 ！");
            return false;
        }
        return true;
    }

    function showDialog(id) {
        var dialog = $("#" + id).data('dialog');
        if (!dialog.element.data('opened')) {
            dialog.open();
        } else {
            dialog.close();
        }
    }

    function confirmdel() {
        var r = confirm("确定要删除吗？");
        if (r) {
            del();
        }
    }

    function getselectedids() {
        var allbox = $(".cbox");
        var selected = "";
        for (var i = 0; i < allbox.length; i++) {
            if (allbox[i].checked) {
                selected = selected + allbox[i].value + ",";
            }
        }
        return selected;
    }

    function move() {
        var selected = getselectedids();
        if (selected === "") {
            alert("请选择移动对象 !");
            return false;
        }
        $("#moveids").val(selected);
        showDialog('movedialog');
        return true;
    }

    function afterMove(data) {
        var msg = data.split(':');
        if (msg[0] === "ok") {
            gotomain();
            return;
        }
        alert(msg[1]);
    }

    function del() {
        var selected = getselectedids();
        if (selected === "") {
            alert("请选择删除对象 !");
            return;
        }
        $.post("/AdminPhoto/Delete", { "ids": selected }, function (data) {
            if (data === "ok") {
                alert("删除成功 !");
                gotomain();
            }
            else {
                alert("删除失败 !");
            }
        });
    }

    function getallcheck() {
        var allbox = $(".cbox");
        if (allbox.length != 0) {
            var selectbox = null;
            var num = 0;
            for (var i = 0; i < allbox.length; i++) {
                if (allbox[i].checked) {
                    num = num + 1;
                    selectbox = allbox[i];
                }
            }
            if (num == 0) {
                return { Num: 0 };
            }
            return { Num: num, SelectBox: selectbox.value };
        } else {
            return { Num: 0 };
        }
    }

    function update() {
        var allcheck = getallcheck();
        if (allcheck.Num === 1) {
            $("#updateform").attr("src", "/AdminPhoto/Update/" + allcheck.SelectBox);
            showDialog('updatedialog');
            return;
        }
        alert("请选择一个修改对象 !");
    }

    function detail(id) {
        $("#detailform").attr("src", "/AdminPhoto/Detail/" + id);
        showDialog('detaildialog');
    }

    function afterCreate(data) {
        var msg = data.split(':');
        alert(msg[1]);
        if (msg[0] === "ok") {
            gotomain();
        }
    }

    function gotomain() {
        window.location.href = "/AdminPhoto/Category/@ViewBag.Type.Id";
    }

    function checkupload(target, type) {
        var filepath = target.value;
        if (filepath === null) {
            return false;
        }
        var ext = filepath.substring(filepath.lastIndexOf("."));
        var allowext = null;
        var allowsize = 0;
        if (type === "img") {
            allowext = [".jpeg", ".jpg", ".png", ".gif", ".ico"];
            allowsize = 20000000;
        } else {
            allowext = [".mp4", ".wmv", ".flv", ".rm", ".swf", ".rmvb"];
            allowsize = 50000000;
        }
        for (var i = 0; i < allowext.length; i++) {
            if (allowext[i] === ext) {
                break;
            }
        }
        if (i === allowext.length) {
            alert("不支持该格式 !");
            return false;
        }
        var size = target.files[0].size;
        if (size > allowsize) {
            alert("所选文件过大 !");
            return false;
        }
        return true;
    }

    function uploadphoto(target) {
        if (checkupload(target, "img")) {
            $("#createform").ajaxSubmit({
                url: "/AdminPhoto/UploadPhoto",
                type: "Post",
                success: function (data) {
                    var str = data.split(':');
                    if (str[0] == "ok") {
                        $("#url").val(str[1]);
                        $("#photoDiv").html("<br /><img src='" + str[1] + "' style='height:200px' />");
                    } else {
                        alert(str[1]);
                    }
                }
            });
        }
    }
</script>

ZKH.Blog.UI.Portal/Views/AdminPhoto/Detail.cshtml
@{
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}
@model ZKH.Blog.Model.PhotoInfo

<div class="container padding20 bg-white" style="width:550px">
    <div style="text-align:center">
        <h3>@Model.Title</h3><br />
        <p style="font-size:small">@Model.SubTime</p>
    </div>
    <hr /><br />
    <p><img src="@Model.Url" style="width:auto" /></p>
    <hr /><br />
    <div class="example" data-text="描述" style="word-break:normal;word-wrap:break-word" >
        @Model.Remark
        <br /><br />
    </div>
</div>

ZKH.Blog.UI.Portal/Views/AdminPhoto/Index.cshtml
@{
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
    ViewBag.Title = "相册管理";
}
@using ZKH.Blog.Model
<div class="padding20 bg-white">
    <h1 class="text-light">相册管理<span class="mif-images place-right"></span></h1>
    <hr class="thin bg-grayLighter">
    <button class="button primary" onclick="showDialog('createdialog')"><span class="mif-plus"></span> 添加相册</button>
    <button class="button success" onclick="update()"> 修改</button>
    <button class="button alert" onclick="confirmdel()"> 删除</button>
    <hr class="thin bg-grayLighter">
    <table class="dataTable border bordered" data-role="datatable" data-auto-width="false">
        <thead>
            <tr>
                <td style="width: 20px"></td>
                <td class="sortable-column" style="width: 100px">ID</td>
                <td class="sortable-column">相册名称</td>
                <td class="sortable-column">描述</td>
                <td class="sortable-column">相片数</td>
                <td class="sortable-column">创建时间</td>
                <td class="sortable-column"></td>
            </tr>
        </thead>
        <tbody>
            @foreach (PhotoType photoType in ViewBag.Types)
            {
                <tr>
                    <td>
                        <label class="input-control checkbox small-check no-margin">
                            <input type="checkbox" class="cbox" value="@photoType.Id">
                            <span class="check"></span>
                        </label>
                    </td>
                    <td>@photoType.Id</td>
                    <td>@photoType.Type</td>
                    <td>@photoType.Remark</td>
                    <td>@photoType.PhotoInfo.Where(a => a.DelFlag == (short)0).Count()</td>
                    <td>@photoType.ModifiedOn</td>
                    <td><a href="/AdminPhoto/Category/@photoType.Id">查看</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div data-role="dialog,draggable" id="createdialog" class="padding20" data-overlay="true" data-close-button="true" data-overlay-color="op-dark" data-overlay-click-close="true">
    <div class="example" data-text="添加相册">
        @using (Ajax.BeginForm("CreateType", "AdminPhoto", new AjaxOptions() { OnSuccess = "afterCreate" }))
        {
            @Html.AntiForgeryToken()
            <label>相册名称</label>
            <input class="input-control full-size required" style="border-style:solid" name="Type" />
            <p id="errormsg"></p>
            <label>描述</label>
            <div class="input-control textarea full-size">
                <textarea name="Remark"></textarea>
            </div>
            <input class="primary" type="submit" value="确定" />
        }
    </div>
</div>
<div data-role="dialog,draggable" id="updatedialog" class="padding20" data-overlay="true" data-close-button="true" data-overlay-color="op-dark" data-overlay-click-close="true">
    <iframe id="updateform" width="500px" height="250px" frameborder="0"></iframe>
</div>
<style type="text/css">
    label.error {
        color: red;
    }
    .field-validation-error {
        color: red;
    }
</style>
<script type="text/javascript">
    $(function () {
        $("form").validate({
            messages: {
                Type: { required: "*必填" }
            },
            errorPlacement: function (error, element) {
                error.appendTo($("#errormsg"));
            }
        });
    });

    function showDialog(id) {
        var dialog = $("#" + id).data('dialog');
        if (!dialog.element.data('opened')) {
            dialog.open();
        } else {
            dialog.close();
        }
    }

    function confirmdel() {
        var r = confirm("确定要删除吗？");
        if (r) {
            del();
        }
    }

    function del() {
        var allbox = $(".cbox");
        var selected = "";
        for (var i = 0; i < allbox.length; i++) {
            if (allbox[i].checked) {
                selected = selected + allbox[i].value + ",";
            }
        }
        if (selected === "") {
            alert("请选择删除对象 !");
            return;
        }
        $.post("DeleteType", { "ids": selected }, function (data) {
            if (data === "ok") {
                alert("删除成功 !");
                gotomain();
            }
            else {
                alert("删除失败 !");
            }
        });
    }

    function getallcheck() {
        var allbox = $(".cbox");
        if (allbox.length != 0) {
            var selectbox = null;
            var num = 0;
            for (var i = 0; i < allbox.length; i++) {
                if (allbox[i].checked) {
                    num = num + 1;
                    selectbox = allbox[i];
                }
            }
            if (num == 0) {
                return { Num: 0 };
            }
            return { Num: num, SelectBox: selectbox.value };
        } else {
            return { Num: 0 };
        }
    }

    function update() {
        var allcheck = getallcheck();
        if (allcheck.Num === 1) {
            $("#updateform").attr("src", "/AdminPhoto/UpdateType/" + allcheck.SelectBox);
            showDialog('updatedialog');
            return;
        }
        alert("请选择一个修改对象 !");
    }

    function afterCreate(data) {
        var msg = data.split(':');
        alert(msg[1]);
        if (msg[0] === "ok") {
            gotomain();
        } 
    }

    function gotomain() {
        window.location.href = "/AdminPhoto/Index";
    }

</script>

ZKH.Blog.UI.Portal/Views/AdminPhoto/Update.cshtml
@{
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}
@model ZKH.Blog.Model.PhotoInfo
<div class="example" data-text="添加图片">
    @using (Ajax.BeginForm("Update", "AdminPhoto", new AjaxOptions() { OnSuccess = "afterUpdate" }))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="Id" value="@Model.Id" />
        <input type="hidden" name="DelFlag" value="@Model.DelFlag" />
        <input type="hidden" name="SubTime" value="@Model.SubTime" />
        <input type="hidden" name="PhotoTypeId" value="@Model.PhotoTypeId" />
            <label>图片名称</label>
            <div>
                <div>
                    <input class="input-control full-size required" style="border-style:solid" name="Title" value="@Model.Title"/>
                </div>
            </div>
            <label>图片</label>
            <div>
                <input type="hidden" class="required" name="Url" id="url" value="@Model.Url"/>
                <div class="input-control file full-size" data-role="input">
                    <input type="file" id="photoinput" accept="image/jpeg,image/gif,image/png" name="photoFile" onchange="uploadphoto(this)">
                    <button class="button"><span class="mif-folder"></span></button>
                </div>
                <label>图片需小于20MB，支持格式：.jpg , .png , .gif , .ico</label>
            </div>
            <div class="cell" id="photoDiv" style="padding:0px 100px">
                <br /><img src='@Model.Url' style='height:200px' />
            </div>
            <br />
            <label>描述</label>
            <div class="input-control textarea full-size">
                <textarea name="Remark">@Model.Remark</textarea>
            </div>
            <input class="primary" type="submit" value="确定" />
            <input class="button link" type="reset" value="重置" />
    }
</div>
<style type="text/css">
    label.error {
        color: red;
    }

    .field-validation-error {
        color: red;
    }
</style>
<script src="~/Scripts/MyAjaxForm.js"></script>
<script type="text/javascript">
    $(function () {
        $("form").validate({
            messages: {
                Title: { required: "*必填" },
                Url: { required: "*请选择图片" }
            },
            errorPlacement: function (error, element) {
                error.appendTo(element.parent().parent());
            }
        });
    });

    function afterUpdate(data) {
        var msg = data.split(':');
        alert(msg[1]);
        if (msg[0] === "ok") {
            window.parent.window.gotomain();
        }
    }

    function checkupload(target, type) {
        var filepath = target.value;
        if (filepath === null) {
            return false;
        }
        var ext = filepath.substring(filepath.lastIndexOf("."));
        var allowext = null;
        var allowsize = 0;
        if (type === "img") {
            allowext = [".jpeg", ".jpg", ".png", ".gif", ".ico"];
            allowsize = 20000000;
        } else {
            allowext = [".mp4", ".wmv", ".flv", ".rm", ".swf", ".rmvb"];
            allowsize = 50000000;
        }
        for (var i = 0; i < allowext.length; i++) {
            if (allowext[i] === ext) {
                break;
            }
        }
        if (i === allowext.length) {
            alert("不支持该格式 !");
            return false;
        }
        var size = target.files[0].size;
        if (size > allowsize) {
            alert("所选文件过大 !");
            return false;
        }
        return true;
    }

    function uploadphoto(target) {
        if (checkupload(target, "img")) {
            $("form").ajaxSubmit({
                url: "/AdminPhoto/UploadPhoto",
                type: "Post",
                success: function (data) {
                    var str = data.split(':');
                    if (str[0] == "ok") {
                        $("#url").val(str[1]);
                        $("#photoDiv").html("<br /><img src='" + str[1] + "' style='height:200px' />");
                    } else {
                        alert(str[1]);
                    }
                }
            });
        }
    }
</script>

ZKH.Blog.UI.Portal/Views/AdminPhoto/UpdateType.cshtml
@{
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}
@model ZKH.Blog.Model.PhotoType
<div class="example" data-text="修改相册">
    @using (Ajax.BeginForm("UpdateType", "AdminPhoto", new AjaxOptions() { OnSuccess = "afterUpdate" }))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" value="@Model.Id" name="Id" />
        <input type="hidden" value="@Model.DelFlag" name="DelFlag" />
        <input type="hidden" value="@Model.SubTime" name="SubTime" />
        <input type="hidden" value="@Model.DelFlag" name="DelFlag" />
        <label>相册名称</label>
            <input class="input-control full-size required" style="border-style:solid" name="Type" value="@Model.Type"/>
            <p id="errormsg"></p>
            <label>描述</label>
            <div class="input-control textarea full-size">
                <textarea name="Remark">@Model.Remark</textarea>
            </div>
            <input class="primary" type="submit" value="确定" />
    }
</div>
<style type="text/css">
    label.error {
        color: red;
    }

    .field-validation-error {
        color: red;
    }
</style>
<script type="text/javascript">
    $(function () {
        $("form").validate({
            messages: {
                Type: { required: "*必填" }
            },
            errorPlacement: function (error, element) {
                error.appendTo($("#errormsg"));
            }
        });
    });
    function afterUpdate(data) {
        var msg = data.split(':');
        alert(msg[1]);
        if (msg[0] === "ok") {
            window.parent.window.gotomain();
        }
    }
</script>